// USER REDUCER TYPES
export const LOADING_USER = 'LOADING_USER'
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED'
export const SET_USER = 'SET_USER'

// DATA REDUCER TYPES
export const LOADING_DATA = 'LOADING_DATA'
export const SET_SENTENCES = 'SET_SENTENCES'
export const POST_SENTENCE = 'POST_SENTENCE'
export const UPDATE_SENTENCE = 'UPDATE_SENTENCE'
export const SET_SENTENCE = 'SET_SENTENCE'
export const DELETE_SENTENCE = 'DELETE_SENTENCE'
export const LIKE_SENTENCE = 'LIKE_SENTENCE'
export const UNLIKE_SENTENCE = 'UNLIKE_SENTENCE'

// UI REDUCER TYPES
export const SET_ERRORS = 'SET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const LOADING_UI = 'LOADING_UI'
export const STOP_LOADING_UI = 'STOP_LOADING_UI'
